pub const CRATE_BLACKLIST: [&'static str; 13] = [
    "cocoa",
    "gleam",
    "glium",
    "idna",
    "libc",
    "openssl",
    "rustc_serialize",
    "serde",
    "serde_json",
    "typenum",
    "unicode_normalization",
    "unicode_segmentation",
    "winapi",
];
