jobs:
# Check formatting
- job: ${{ parameters.name }}
  displayName: Run tests on
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-16.04'
      mac:
        imageName: 'macos-10.14'
      windows:
        imageName: 'vs2017-win2016'
  pool:
    vmImage: $(imageName)
  steps:
    - template: azure-install-rust.yml
      parameters:
        rust_version: ${{ parameters.rust }}
    - script: |
        rustup component add rust-src rust-analysis rustc-dev
      displayName: Install distributed Rust source code for Racer autocompletion
    - ${{ each crate in parameters.crates }}:
      - script: cargo test -v
        displayName: Run tests - ${{ crate.key }}
        workingDirectory: $(Build.SourcesDirectory)/${{ crate.key }}
      - ${{ each extra in crate.value }}:
        - script: cargo test -v ${{ extra.args }} ${{ extra.test_name }} -- ${{ extra.test_args }}
          displayName: Run tests - ${{ crate.key }} - ${{ extra.test_name }}
          workingDirectory: $(Build.SourcesDirectory)/${{ crate.key }}
